version: "3.8"

services:  
  
  user-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: user-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=logPaSs#123$32
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql    
    restart: always     

volumes:
  sql_data:
    driver: local